### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Greywolfe69** [OpenDAoC/OpenDAoC-Core#29]
Having a lot of errors appear after following the steps for setting up the server. Also installed on fresh windows 10 computer.
any suggestions?

[12:06:59,002] [ERROR] [DOL.Database.ObjectDatabase] SelectAllObjects: DataObject Type (DOL.Database.ServerProperty) not registered !
[12:06:59,003] [ERROR] [DOL.GS.GameServer] Server Properties Lookup: Error While Initialization
DOL.Database.DatabaseException: Table DOL.Database.ServerProperty is not registered for Database Connection...
   at DOL.Database.ObjectDatabase.SelectAllObjects[TObject]() in C:\opendaoc-core\DOLDatabase\ObjectDatabase.cs:line 761
   at DOL.GS.ServerProperties.Properties.get_AllDomainProperties() in C:\OpenDAoC-Core\GameServer\serverproperty\ServerProperties.cs:line 2933
   at DOL.GS.ServerProperties.Properties.InitProperties() in C:\OpenDAoC-Core\GameServer\serverproperty\ServerProperties.cs:line 45
   at DOL.GS.GameServer.InitComponent(Action componentInitMethod, String text) in C:\OpenDAoC-Core\GameServer\GameServer.cs:line 1225
[12:06:59,004] [INFO] [DOL.GS.GameServer] Server Properties Lookup: False
[12:06:59,005] [INFO] [DOL.GS.GameServer] GameServer.Stop() - enter method
[12:06:59,010] [DEBUG] [DOL.Network.BaseServer] Stopping server! - Cleaning up client list!
[12:06:59,022] [INFO] [DOL.Network.BaseServer] Server stopped
[12:06:59,025] [DEBUG] [DOL.GS.WorldMgr] Stopping region managers...
[12:06:59,028] [DEBUG] [DOL.GS.WorldMgr] Region managers stopped.
[12:06:59,028] [INFO] [DOL.GS.GameServer] Saving database...
[12:06:59,029] [DEBUG] [DOL.GS.GameServer] Save ThreadId=1
[12:06:59,031] [DEBUG] [DOL.GS.DoorMgr] Saving keep doors...
[12:06:59,032] [DEBUG] [DOL.GS.GuildMgr] Saving all guilds...
[12:06:59,033] [DEBUG] [DOL.GS.BoatMgr] Saving all boats...
[12:06:59,035] [INFO] [DOL.GS.GameServer] Saving database complete!
[12:06:59,035] [INFO] [DOL.GS.GameServer] Saved all databases and 0 players in 16ms
Crafting Progress Saved for: 0
[12:06:59,036] [DEBUG] [DOL.GS.WorldMgr] Stopping region managers...
[12:06:59,036] [DEBUG] [DOL.GS.WorldMgr] Region managers stopped.
[12:06:59,037] [ERROR] [DOL.GS.GameServer] Failed to start the server
System.NullReferenceException: Object reference not set to an instance of an object.
   at DOL.GS.GameLoop.Exit() in C:\OpenDAoC-Core\GameServer\managers\GameLoopManager\GameLoop.cs:line 32
   at DOL.GS.GameServer.Stop() in C:\OpenDAoC-Core\GameServer\GameServer.cs:line 1319
   at DOL.GS.GameServer.InitComponent(Action componentInitMethod, String text) in C:\OpenDAoC-Core\GameServer\GameServer.cs:line 1238
   at DOL.GS.GameServer.Start() in C:\OpenDAoC-Core\GameServer\GameServer.cs:line 616

**Comment by bm01** [comment]
Hey.
The exception at the bottom of your log and the following ones if there are any can be ignored, it's not supposed to happen but at that point the server already failed to start.
It looks like the server can't connect or communicate with your DB. Double check your serverconfig.xml.

**Comment by claitz** [comment]
What bm01 said :)! Join our discord to get support on your configuration.
